
Vagrant.configure(2) do |config|
   config.vm.define "c7" do |c7|
	c7.vm.provider "VirtualBox"
	#db.vm.gui = true
	c7.vm.box = "centos7"
	#db.vm.network "public_network", bridge: "wlp3s0", use_dhcp_assigned_default_route: true
	#c7.vm.network :private_network, ip: "192.168.57.120"
	c7.vm.network :private_network, type: "dhcp"
	#db.vm.network "private_network", ip: "192.168.56.120", auto_config: false
	c7.vm.network "public_network"
	#c7.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
	#db.vm.provision "shell", path: "C:\Users\Sergei.Saenko\git\task\scripts\mariadb.sh"
	c7.ssh.username = "vagrant"
    c7.ssh.password = "vagrant"
   end
 end
