- hosts: new
  remote_user: faktor
  become: yes
  tasks:
  - name: All package upgrade
    yum: name='*' state=latest
  - name: Additional package installation
    yum: name={{item}} state=latest update_cache=yes
    with_items:
        - firewalld
        - nmap
        - htop
        - bind-utils
    notify:
     - selinux disabled
     - firewall enabled
     - firewall port opening
  
  - name: EPEL repository installation
    yum_repository: 
    name: epel 
    description: EPEL YUM repo 
    file: epel.repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    enabled: no
  
  - name: NOPASSWD for wheel group in sudoers
    replace:
    path: /etc/sudoers
    regexp: ''^%wheel''
    replace: '\%wheel  ALL=(ALL)  NOPASSWD: ALL'
    backup: yes

  handlers:
  - name: selinux disabled
    selinux: state=disabled

  - name: firewall enabled
    service: name=firewalld enabled=yes state=restarted

  - name: firewall port opening
    firewalld: service={{item}} state=enabled permanent=true zone=public immediate=yes
    with_items:
        - http
        - https
        - ssh