- hosts: all
  remote_user: sergei
  become: yes
  tasks:
  - name: All package upgrade
    yum: name='*' state=latest
   
  - name: repository installation
    yum_repository: 
     name: epel  
     description: EPEL YUM repo 
     file: epel.repo
     baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
     mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
     enabled: no
     gpgcheck: no
  
  - name: Additional package installation
    yum: name={{item}} state=latest update_cache=yes enablerepo=epel
    with_items:
      - firewalld
      - nmap
      - htop
      - bind-utils
    notify:
      - selinux disabled
      - firewall enabled
      - firewall port opening

  handlers:
  - name: selinux disabled
    selinux: state=disabled

  - name: firewall enabled
    service: name=firewalld enabled=yes state=restarted

  - name: firewall port opening
    firewalld: service={{item}} state=enabled permanent=true zone=public immediate=yes
    with_items:
       - http
       - https
       - ssh
