--- # Variable test list
- hosts: jenkins
  remote_user: faktor
  become: yes
  tasks:
# JDK installation
  - name: Installation of JDK
    yum: name=java-1.8.0-openjdk state=latest

# Jenkins installation
  - name: Install Jenkins repo
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  - name: Install GPG key for Jenkins repository
    rpm_key: key=https://jenkins-ci.org/redhat/jenkins-ci.org state=present
  - name: Update all packages to latest version
    yum: name='*' state=latest
  - name: Installation of Jenkins
    yum: name=jenkins state=present
    notify:
    - jenkins service on
  handlers:
  - name: jenkins service on
    service: name=jenkins enabled=yes state=restarted


# Firewall installation
  - name: Installation of FirewallD package
    yum: name=firewalld state=latest 
